#!/usr/bin/env python3
"""
MDP Generator Module for GROMACS PPI Analysis

Generates GROMACS MDP (Molecular Dynamics Parameter) files for various
simulation types: energy minimization, equilibration, and production MD.
"""

from pathlib import Path
from typing import Optional, Union, Dict, Any
from dataclasses import dataclass, field


@dataclass
class MDPConfig:
    """Configuration for MDP file generation."""
    
    # Energy minimization
    em_steps: int = 5000
    em_tolerance: float = 100.0  # kJ/mol/nm
    em_step_size: float = 0.01
    
    # MD general
    timestep: float = 0.002  # ps (2 fs)
    temperature: float = 300.0  # K
    pressure: float = 1.0  # bar
    
    # Equilibration
    nvt_steps: int = 50000  # 100 ps
    npt_steps: int = 50000  # 100 ps
    
    # Production MD
    md_steps: int = 250000  # 500 ps
    
    # Output frequency (in steps)
    nstxout: int = 500
    nstvout: int = 500
    nstenergy: int = 500
    nstlog: int = 500
    nstxout_compressed: int = 1000
    
    # Cutoffs
    rcoulomb: float = 1.0  # nm
    rvdw: float = 1.0  # nm
    
    # Neighbor list
    nstlist: int = 20


def generate_em_mdp(output_path: Optional[Union[str, Path]] = None,
                    config: Optional[MDPConfig] = None) -> str:
    """
    Generate energy minimization MDP file content.
    
    Args:
        output_path: Optional path to write the MDP file
        config: Optional MDPConfig (uses defaults if None)
    
    Returns:
        MDP file content as string
    """
    cfg = config or MDPConfig()
    
    content = f"""; Energy Minimization Parameters
; Generated by gromacs_utils.mdp_generator

integrator      = steep         ; Steepest descent minimization
emtol           = {cfg.em_tolerance}         ; Stop when max force < {cfg.em_tolerance} kJ/mol/nm
emstep          = {cfg.em_step_size}          ; Energy step size
nsteps          = {cfg.em_steps}          ; Maximum number of steps

; Neighbor searching
nstlist         = 10            ; Frequency to update neighbor list
cutoff-scheme   = Verlet
ns_type         = grid          ; Method to determine neighbor list

; Electrostatics
coulombtype     = PME           ; Particle Mesh Ewald for long-range electrostatics
rcoulomb        = {cfg.rcoulomb}           ; Short-range electrostatic cutoff (nm)

; VdW
vdwtype         = Cut-off
rvdw            = {cfg.rvdw}           ; Short-range van der Waals cutoff (nm)

; Periodic boundary conditions
pbc             = xyz           ; 3D PBC
"""
    
    if output_path:
        Path(output_path).write_text(content)
    
    return content


def generate_nvt_mdp(output_path: Optional[Union[str, Path]] = None,
                     config: Optional[MDPConfig] = None,
                     position_restraints: bool = True) -> str:
    """
    Generate NVT equilibration MDP file content.
    
    Args:
        output_path: Optional path to write the MDP file
        config: Optional MDPConfig (uses defaults if None)
        position_restraints: Whether to include position restraints
    
    Returns:
        MDP file content as string
    """
    cfg = config or MDPConfig()
    
    define_line = "define          = -DPOSRES      ; Position restrain the protein" if position_restraints else ""
    
    content = f"""; NVT Equilibration Parameters
; Generated by gromacs_utils.mdp_generator
{define_line}

integrator      = md            ; Leap-frog integrator
nsteps          = {cfg.nvt_steps}         ; {cfg.nvt_steps * cfg.timestep:.0f} ps
dt              = {cfg.timestep}         ; {cfg.timestep * 1000:.0f} fs timestep

; Output control
nstxout         = {cfg.nstxout}           ; Save coordinates every {cfg.nstxout * cfg.timestep:.1f} ps
nstvout         = {cfg.nstvout}           ; Save velocities every {cfg.nstvout * cfg.timestep:.1f} ps
nstenergy       = {cfg.nstenergy}           ; Save energies every {cfg.nstenergy * cfg.timestep:.1f} ps
nstlog          = {cfg.nstlog}           ; Update log file every {cfg.nstlog * cfg.timestep:.1f} ps
nstxout-compressed = {cfg.nstxout_compressed}        ; Save compressed coordinates

; Bond parameters
continuation    = no            ; First dynamics run
constraint_algorithm = lincs    ; Holonomic constraints
constraints     = h-bonds       ; H-bonds constrained
lincs_iter      = 1             ; Accuracy of LINCS
lincs_order     = 4             ; Also related to accuracy

; Neighbor searching
cutoff-scheme   = Verlet
nstlist         = {cfg.nstlist}            ; Neighbor list update frequency
rcoulomb        = {cfg.rcoulomb}           ; Short-range electrostatic cutoff (nm)
rvdw            = {cfg.rvdw}           ; Short-range van der Waals cutoff (nm)

; Electrostatics
coulombtype     = PME           ; Particle Mesh Ewald
pme_order       = 4             ; Cubic interpolation
fourierspacing  = 0.12          ; Grid spacing for FFT

; Temperature coupling
tcoupl          = V-rescale     ; Modified Berendsen thermostat
tc-grps         = Protein Non-Protein ; Two coupling groups
tau_t           = 0.1     0.1   ; Time constant (ps)
ref_t           = {cfg.temperature:.0f}     {cfg.temperature:.0f}   ; Reference temperature (K)

; Pressure coupling - off for NVT
pcoupl          = no

; Periodic boundary conditions
pbc             = xyz           ; 3D PBC

; Velocity generation
gen_vel         = yes           ; Generate velocities from Maxwell distribution
gen_temp        = {cfg.temperature:.0f}           ; Temperature for velocity generation
gen_seed        = -1            ; Random seed
"""
    
    if output_path:
        Path(output_path).write_text(content)
    
    return content


def generate_npt_mdp(output_path: Optional[Union[str, Path]] = None,
                     config: Optional[MDPConfig] = None,
                     position_restraints: bool = True) -> str:
    """
    Generate NPT equilibration MDP file content.
    
    Args:
        output_path: Optional path to write the MDP file
        config: Optional MDPConfig (uses defaults if None)
        position_restraints: Whether to include position restraints
    
    Returns:
        MDP file content as string
    """
    cfg = config or MDPConfig()
    
    define_line = "define          = -DPOSRES      ; Position restrain the protein" if position_restraints else ""
    
    content = f"""; NPT Equilibration Parameters
; Generated by gromacs_utils.mdp_generator
{define_line}

integrator      = md            ; Leap-frog integrator
nsteps          = {cfg.npt_steps}         ; {cfg.npt_steps * cfg.timestep:.0f} ps
dt              = {cfg.timestep}         ; {cfg.timestep * 1000:.0f} fs timestep

; Output control
nstxout         = {cfg.nstxout}           ; Save coordinates
nstvout         = {cfg.nstvout}           ; Save velocities
nstenergy       = {cfg.nstenergy}           ; Save energies
nstlog          = {cfg.nstlog}           ; Update log file
nstxout-compressed = {cfg.nstxout_compressed}        ; Save compressed coordinates

; Bond parameters
continuation    = yes           ; Continuing after NVT
constraint_algorithm = lincs
constraints     = h-bonds
lincs_iter      = 1
lincs_order     = 4

; Neighbor searching
cutoff-scheme   = Verlet
nstlist         = {cfg.nstlist}
rcoulomb        = {cfg.rcoulomb}
rvdw            = {cfg.rvdw}

; Electrostatics
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.12

; Temperature coupling
tcoupl          = V-rescale
tc-grps         = Protein Non-Protein
tau_t           = 0.1     0.1
ref_t           = {cfg.temperature:.0f}     {cfg.temperature:.0f}

; Pressure coupling
pcoupl          = Parrinello-Rahman
pcoupltype      = isotropic
tau_p           = 2.0           ; Time constant (ps)
ref_p           = {cfg.pressure}           ; Reference pressure (bar)
compressibility = 4.5e-5        ; Isothermal compressibility of water

; Periodic boundary conditions
pbc             = xyz

; Velocity generation - no, continuing from NVT
gen_vel         = no
"""
    
    if output_path:
        Path(output_path).write_text(content)
    
    return content


def generate_md_mdp(output_path: Optional[Union[str, Path]] = None,
                    config: Optional[MDPConfig] = None) -> str:
    """
    Generate production MD MDP file content.
    
    Args:
        output_path: Optional path to write the MDP file
        config: Optional MDPConfig (uses defaults if None)
    
    Returns:
        MDP file content as string
    """
    cfg = config or MDPConfig()
    
    content = f"""; Production MD Parameters
; Generated by gromacs_utils.mdp_generator

integrator      = md            ; Leap-frog integrator
nsteps          = {cfg.md_steps}        ; {cfg.md_steps * cfg.timestep:.0f} ps
dt              = {cfg.timestep}         ; {cfg.timestep * 1000:.0f} fs timestep

; Output control
nstxout         = 0             ; Don't save .trr coordinates (use .xtc)
nstvout         = 0             ; Don't save .trr velocities
nstfout         = 0             ; Don't save forces
nstenergy       = {cfg.nstenergy}           ; Save energies
nstlog          = {cfg.nstlog}           ; Update log file
nstxout-compressed = {cfg.nstxout_compressed}       ; Save .xtc coordinates

; Bond parameters
continuation    = yes           ; Continuing after NPT
constraint_algorithm = lincs
constraints     = h-bonds
lincs_iter      = 1
lincs_order     = 4

; Neighbor searching
cutoff-scheme   = Verlet
nstlist         = {cfg.nstlist}
rcoulomb        = {cfg.rcoulomb}
rvdw            = {cfg.rvdw}

; Electrostatics
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.12

; Temperature coupling
tcoupl          = V-rescale
tc-grps         = Protein Non-Protein
tau_t           = 0.1     0.1
ref_t           = {cfg.temperature:.0f}     {cfg.temperature:.0f}

; Pressure coupling
pcoupl          = Parrinello-Rahman
pcoupltype      = isotropic
tau_p           = 2.0
ref_p           = {cfg.pressure}
compressibility = 4.5e-5

; Periodic boundary conditions
pbc             = xyz

; Velocity generation - no
gen_vel         = no
"""
    
    if output_path:
        Path(output_path).write_text(content)
    
    return content


def generate_ie_mdp(output_path: Optional[Union[str, Path]] = None,
                    config: Optional[MDPConfig] = None) -> str:
    """
    Generate interaction energy calculation MDP file content.
    
    Args:
        output_path: Optional path to write the MDP file
        config: Optional MDPConfig (uses defaults if None)
    
    Returns:
        MDP file content as string
    """
    cfg = config or MDPConfig()
    
    content = f"""; Interaction Energy Calculation (rerun)
; Generated by gromacs_utils.mdp_generator

integrator      = md
nsteps          = 0
dt              = {cfg.timestep}

; Energy output - detailed
nstenergy       = 1
nstlog          = 1

; Energy groups for interaction energy calculation
energygrps      = ChainA ChainB

; Neighbor searching
cutoff-scheme   = Verlet
nstlist         = {cfg.nstlist}
rcoulomb        = {cfg.rcoulomb}
rvdw            = {cfg.rvdw}

; Electrostatics
coulombtype     = PME
pme_order       = 4
fourierspacing  = 0.12

; PBC
pbc             = xyz
"""
    
    if output_path:
        Path(output_path).write_text(content)
    
    return content


def generate_all_mdp_files(output_dir: Union[str, Path],
                           config: Optional[MDPConfig] = None) -> Dict[str, Path]:
    """
    Generate all MDP files for a complete MD workflow.
    
    Args:
        output_dir: Directory to write MDP files
        config: Optional MDPConfig (uses defaults if None)
    
    Returns:
        Dictionary mapping MDP type to file path
    """
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    
    files = {}
    
    files['em'] = output_path / 'em.mdp'
    generate_em_mdp(files['em'], config)
    
    files['nvt'] = output_path / 'nvt.mdp'
    generate_nvt_mdp(files['nvt'], config)
    
    files['npt'] = output_path / 'npt.mdp'
    generate_npt_mdp(files['npt'], config)
    
    files['md'] = output_path / 'md.mdp'
    generate_md_mdp(files['md'], config)
    
    files['ie'] = output_path / 'ie.mdp'
    generate_ie_mdp(files['ie'], config)
    
    return files


# Command-line interface
if __name__ == '__main__':
    import argparse
    
    parser = argparse.ArgumentParser(description='Generate GROMACS MDP files')
    parser.add_argument('type', choices=['em', 'nvt', 'npt', 'md', 'ie', 'all'],
                        help='Type of MDP file to generate')
    parser.add_argument('-o', '--output', help='Output file or directory')
    parser.add_argument('--em-steps', type=int, default=5000, help='EM steps')
    parser.add_argument('--nvt-steps', type=int, default=50000, help='NVT steps')
    parser.add_argument('--npt-steps', type=int, default=50000, help='NPT steps')
    parser.add_argument('--md-steps', type=int, default=250000, help='MD steps')
    parser.add_argument('--temperature', type=float, default=300, help='Temperature (K)')
    
    args = parser.parse_args()
    
    config = MDPConfig(
        em_steps=args.em_steps,
        nvt_steps=args.nvt_steps,
        npt_steps=args.npt_steps,
        md_steps=args.md_steps,
        temperature=args.temperature
    )
    
    if args.type == 'all':
        output_dir = args.output or '.'
        files = generate_all_mdp_files(output_dir, config)
        for name, path in files.items():
            print(f"Generated: {path}")
    else:
        generators = {
            'em': generate_em_mdp,
            'nvt': generate_nvt_mdp,
            'npt': generate_npt_mdp,
            'md': generate_md_mdp,
            'ie': generate_ie_mdp
        }
        
        output = args.output or f'{args.type}.mdp'
        generators[args.type](output, config)
        print(f"Generated: {output}")
